### ISSUE TITLE
Problems with User Management

### ISSUE THREAD

**Issue by mendicino-dev** [openremote/openremote#1647]
I am experiencing several issues with user management in OpenRemote (on version 1.2.1, 1.2.2 and 1.2.3). These problems persist across multiple tests on different browsers and systems, including Mac (Intel & Apple Silicon) and Linux Debian.

The key issues I encountered are:

1. **Blank Screen After Login:**

- Users created through the OpenRemote Manager are unable to log in properly.
- After entering their credentials, they are redirected to a blank page instead of the dashboard.
- The admin user (default) does not experience this issue, only newly created users.

2. **User Creation Form Resets Fields:**

- When filling out the user creation form in OpenRemote Manager, some fields (such as username and email) get randomly reset before submission.
- This forces the user to manually re-enter the information multiple times.

3. **User Creation Fails or is Incomplete:**

- In many cases, user creation fails without a clear error message.
- When the user is successfully created, they often lack the roles and permissions that were set during the creation process.
- This forces manual intervention in Keycloak to correct the missing roles.

I have tried multiple debugging steps:

- Testing on different browsers (Chrome, Firefox, Safari).
- Running OpenRemote on different machines (Mac Intel, Apple Silicon, and Linux Debian).
- Ensuring that the Keycloak realm and roles are correctly configured.
- Checking logs for errors related to user authentication and permissions.

I am unsure whether these issues are due to a misconfiguration on my part or if they are known bugs. Below is the docker-compose.yml file I am using for my deployment.

**Docker Compose Configuration**
(Email and domain information anonymized for privacy)
```
volumes:
  proxy-data:
  manager-data:
  postgresql-data:

services:

  proxy:
    image: openremote/proxy:${PROXY_VERSION:-latest}
    restart: always
    depends_on:
      manager:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
      - "8883:8883"
      - "127.0.0.1:8404:8404"
    volumes:
      - proxy-data:/deployment
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      LE_EMAIL: [REDACTED]
      DOMAINNAME: [REDACTED]
      DOMAINNAMES: [REDACTED]

  postgresql:
    restart: always
    image: openremote/postgresql:${POSTGRESQL_VERSION:-latest}
    shm_size: 128mb
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - manager-data:/storage

  keycloak:
    restart: always
    image: openremote/keycloak:${KEYCLOAK_VERSION:-latest}
    depends_on:
      postgresql:
        condition: service_healthy
    volumes:
      - ./deployment:/deployment
    environment:
      KEYCLOAK_ADMIN_PASSWORD: ${OR_ADMIN_PASSWORD:-secret}
      KC_HOSTNAME: [REDACTED]
      KC_HOSTNAME_PORT: -1
      KC_THEME: openremote

  manager:
    restart: always
    image: openremote/manager:1.2.1
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - "127.0.0.1:8405:8405"
    environment:
      OR_SETUP_TYPE:
      OR_ADMIN_PASSWORD:
      OR_SETUP_RUN_ON_RESTART:
      OR_EMAIL_HOST:
      OR_EMAIL_USER:
      OR_EMAIL_PASSWORD:
      OR_EMAIL_X_HEADERS:
      OR_EMAIL_FROM:
      OR_EMAIL_ADMIN:
      OR_METRICS_ENABLED: ${OR_METRICS_ENABLED:-true}
      OR_HOSTNAME: [REDACTED]
      OR_ADDITIONAL_HOSTNAMES:
      OR_SSL_PORT: 443
      OR_DEV_MODE: ${OR_DEV_MODE:-false}
    volumes:
      - ./deployment:/deployment
      - ./deployment/keycloak/themes:/opt/keycloak/themes
      - manager-data:/storage
```
**Expected Behavior**

- Users should be able to log in successfully without encountering a blank page.
- The user creation form should retain all field values until submission.
- Users should be created with the correct roles and permissions as configured in OpenRemote Manager.

**Actual Behavior**

- Users see a blank screen after logging in.
- The user creation form resets fields, forcing repeated input.
- Users lack roles and permissions after creation.

**Questions**

- Are these known issues with OpenRemote from 1.2.1 to 1.2.3?
- Is there something wrong with my docker-compose.yml configuration?
- Could these issues be related to Keycloak misconfigurations?

Any help or guidance would be appreciated. Thanks in advance!
