### ISSUE TITLE
Impossible to see the map of my area via documentation

### ISSUE THREAD

**Issue by jcheca** [openremote/openremote#435]
I cannot render the map of my area. These are the steps I have taken in case they weren't the right ones.
- From maptiler download OpenStreetMap vector tiles Cadiz, for instance as input.mbtiles file.
- Follow instructions to extract smaller file tiles from Developer Guide: Working on map to generate output.mbtiles renaming to mapdata.mbtiles
- On docker-compose i have:

```
  manager:
    restart: always
    image: openremote/manager:${MANAGER_VERSION:-latest}
    depends_on:
      keycloak:
        condition: service_healthy
    volumes:
      - ./deployment:/deployment
    environment:
      DEV_MODE: ${DEV_MODE:-false}
      SETUP_ADMIN_PASSWORD: ${SETUP_ADMIN_PASSWORD:-secret}
```
- Move smalller file mapdata.mbtiles files to local /deployments/map as the docker mounted volume.
- No mapsettings.json defined, but if defined notyhing (center maps and bounds defined too) happens. I do not know where to find mapsettings.json corresponding to Openstreetmap vector downloaded.
- No error on manager container via logs file mapdata.mbtiles is found and loaded when reload container.
- Nothing display y map area. No maps in the interface.

Any help would be appreciated !! I need help. Thanks in advance.
